// <auto-generated />
using System;
using BatchApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BatchApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BatchApp.Models.ACL", b =>
                {
                    b.Property<string>("ReadUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BatchModelBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReadUser");

                    b.HasIndex("BatchModelBatchId");

                    b.ToTable("ACLs");
                });

            modelBuilder.Entity("BatchApp.Models.Atribute", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("BatchModelBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("BatchModelBatchId");

                    b.ToTable("Atributes");
                });

            modelBuilder.Entity("BatchApp.Models.BatchModel", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("BatchApp.Models.ACL", b =>
                {
                    b.HasOne("BatchApp.Models.BatchModel", null)
                        .WithMany("ACLs")
                        .HasForeignKey("BatchModelBatchId");
                });

            modelBuilder.Entity("BatchApp.Models.Atribute", b =>
                {
                    b.HasOne("BatchApp.Models.BatchModel", null)
                        .WithMany("Atributes")
                        .HasForeignKey("BatchModelBatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
